apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: api
build:
  artifacts:
    - image: gcr.io/keatproj/keat-server
      docker:
        dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
      - k8s/manifests/crd.yaml
      - k8s/manifests/deployment.yaml
      - k8s/manifests/service-account.yaml
      - k8s/manifests/service.yaml
portForward:
  - resourceType: deployment
    resourceName: keat-server
    namespace: default
    port: 8080
