apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: features.keat.io
spec:
  scope: Namespaced
  group: keat.io
  names:
    kind: Feature
    listKind: FeatureList
    singular: feature
    plural: features
    shortNames:
      - feat
      - feats
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Enabled
          type: boolean
          jsonPath: .spec.enabled
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                enabled:
                  type: boolean
                audiences:
                  type: array
                  items:
                    type: string
              required:
                - enabled
            status:
              type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: audiences.keat.io
spec:
  scope: Namespaced
  group: keat.io
  names:
    kind: Audience
    listKind: AudienceList
    singular: audience
    plural: audiences
    shortNames:
      - aud
      - auds
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                kind:
                  type: string
                  enum: ["static", "random"]
                members:
                  type: array
                  items:
                    type: string
                percentage:
                  type: number
              required:
                - kind
            status:
              type: object
