apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.keat.io
spec:
  scope: Namespaced
  group: keat.io
  names:
    kind: Application
    listKind: ApplicationList
    singular: application
    plural: applications
    shortNames:
      - app
      - apps
  preserveUnknownFields: false
  versions:
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              x-kubernetes-preserve-unknown-fields: true
              type: object
