apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crd.yaml
- service.yaml
- service-account.yaml
- deployment.yaml
images:
- name: gcr.io/keatproj/keat-server
  newName: gcr.io/keatproj/keat-server
  newTag: 0.2.0-alpha.4
