apiVersion: v1
kind: Service
metadata:
  name: keat-server
spec:
  type: ClusterIP
  selector:
    app: keat-server
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 8080
