apiVersion: v1
kind: ServiceAccount
metadata:
  name: kea-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keat-server
rules:
  - apiGroups: ["keat.io"]
    resources: ["applications"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keat-server
roleRef:
  kind: Role
  name: keat-server
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: keat-server
